<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Naitrust.Api</RootNamespace>
    <UserSecretsId>69efdf19-2299-414f-8ebb-abdf1df7c850</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.*" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.*" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.*" />
    <PackageReference Include="StackExchange.Redis" Version="2.7.*" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Naitrust.Application\Naitrust.Application.csproj" />
    <ProjectReference Include="..\Naitrust.Domain\Naitrust.Domain.csproj" />
    <ProjectReference Include="..\Naitrust.Infrastructure\Naitrust.Infrastructure.csproj" />
  </ItemGroup>

</Project>
