<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Naitrust.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.*" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.20.*" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Naitrust.Domain\Naitrust.Domain.csproj" />
  </ItemGroup>

</Project>
