<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Naitrust.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.*" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="8.0.*" />
  </ItemGroup>

</Project>
